spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PW}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  ai:
    anthropic:
      api-key: ${CLAUDE_KEY}
      chat:
        options:
          model: claude-3-5-sonnet-20241022
          temperature: 0
          max-tokens: 1024
